<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAi2xiic\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAi2xiic/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAi2xiic.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAi2xiic\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAi2xiic\appProdProjectContainer([
    'container.build_hash' => 'Ai2xiic',
    'container.build_id' => '5f36250b',
    'container.build_time' => 1648372225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAi2xiic');
